language: php
php:
- 5.4
before_script:
- phpenv rehash
# prepare redCORE .travis scripts
- cd redCORE
- composer update
- git submodule init
- git submodule update
- cd ..

script:
- php redCORE/.travis/misseddebugcodechecker.php component/ libraries/ modules/ plugins/
- php redCORE/.travis/phppec.php component/ libraries/ modules/ plugins/
- php redCORE/.travis/phpmd.php component/ libraries/ modules/ plugins/
- php redCORE/.travis/phpcs.php
notifications:
  slack:
    secure: QMZp50B4Y+1SMnwMr7kNhffF/u6fnX2riwyHglChvNvPTn9KE2BwLwBbPgewE5U8L+hJwRsKEv8c28L3WtjcGSBBrpxTOig21LBfd5lDhPHExhHTAjWtVPVt0pYWqvitgHJ5efXOqve19UqR1SuI9JCpwRsLwq9jPWmzCZ5Sdxw=
