language: php

php:
  - 5.3

before_script:
  - pear install PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - pear install phpunit/phpcpd
  - phpenv rehash

script:
  - find ./component -name '*.php' -exec php -l {} \;
  - find ./modules -name '*.php' -exec php -l {} \;
  - phing -f .travis.xml